# Generated by Django 4.1.6 on 2024-05-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumaguaAPP', '0003_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
