# Generated by Django 4.1.6 on 2024-05-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumaguaAPP', '0004_reporte_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='dato_extra',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='descripcion',
        ),
    ]
